name: .NET

on: [ pull_request, push ]

jobs:
  build-pcmhammer:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - uses: microsoft/setup-msbuild@v1.0.2
      name: Setup MSBuild Path

    - uses: NuGet/setup-nuget@v1.0.2
      name: Setup NuGet
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - run: nuget restore Apps/PcmApps.sln
      name: Restore NuGet Packages

    - run: msbuild Apps/PcmApps.sln
      name: Build Applications

    - uses: actions/upload-artifact@v2
      with:
        name: PCMHacks-${{github.sha}}
        path: |
          Apps\PcmHammer\bin\Debug\
          Apps\PcmLogger\bin\Debug\
          Apps\VpwExplorer\bin\Debug\

  build-kernel-P01:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - run: sudo apt-get install -y gcc-m68k-linux-gnu make
      name: Install m68k Compiler and Make tool

    - run: cd Kernels && make PREFIX=/usr/bin/m68k-linux-gnu- pcm=P01
      name: Build Kernel Source Code for P01 PCM

  build-kernel-P10:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - run: sudo apt-get install -y gcc-m68k-linux-gnu make
      name: Install m68k Compiler and Make tool

    - run: cd Kernels && make PREFIX=/usr/bin/m68k-linux-gnu- pcm=P10
      name: Build Kernel Source Code for P10 PCM

  build-kernel-P12:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - run: sudo apt-get install -y gcc-m68k-linux-gnu make
      name: Install m68k Compiler and Make tool

    - run: cd Kernels && make PREFIX=/usr/bin/m68k-linux-gnu- pcm=P12
      name: Build Kernel Source Code for P12 PCM
