<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Tests</AssemblyTitle>
    <Product>Tests</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PcmLibrary\PcmLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DynamicExpresso.Core" Version="2.16.1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.*" />
    <PackageReference Include="Microsoft.Testing.Extensions.Telemetry" Version="1.4.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" Version="1.4.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" Version="1.4.0" />
    <PackageReference Include="Microsoft.Testing.Platform" Version="1.4.0" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="1.4.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>
</Project>